"""What named declarations actually mean in this app."""

DECL = {
    "api": "Creates the one Axios client every screen imports. baseURL is VITE_API_URL or http://localhost:4000/api. withCredentials sends cookies so /auth/refresh can read the refresh cookie.",
    "FUNDING_URL": "The Buy Me a Coffee URL injected at build time from .github/FUNDING.yml by vite.config.ts as __FUNDING_URL__.",
    "FEEDBACK_URL": "Hard-coded link to https://www.jumpybrain.com/#feedback. The banner, sidebar, and top bar all open it in a new tab.",
    "NAV_ITEMS": "The four primary routes: / Today, /todo Tasks, /calendar Schedule, /dashboard Progress. Sidebar, TopBar, and BottomNav all map this array.",
    "SECONDARY_NAV": "Routes tucked under More: /focus, /blocking, /mindful, /deadline, /settings.",
    "CONNECTORS": "Gmail, Slack, and Google Calendar. Each entry knows the OAuth URL path and the sync path the buttons call.",
    "GOOGLE_CLIENT_ID": "Vite env VITE_GOOGLE_CLIENT_ID. If it is missing, Auth shows a disabled button instead of Google's widget.",
    "ENERGY_LEVELS": "Five faces indexed 0–4, stored as levels 1–5: Exhausted, Low, Okay, Good, Peak. EnergyControl is the only writer; EnergyContext holds the number.",
    "CIRCUMFERENCE": "Circumference of the timer ring (radius 90). strokeDashoffset uses it so the ring empties as seconds fall.",
    "MODES": "In FocusTimer, Pomodoro is 25/5 and Deep Work is 50/10. In Mindfulness the live MODES (the third copy, after line 252) are three mp3s. The earlier MODES are inside comments and never run.",
    "STATES": "Focus overlay state machine: idle, focused, distracted (left the tab, waiting 800ms), alert (show the nudge).",
    "messages": "Five encouragement strings keyed by context: tab-change, day-start, day-end, task-complete, task-incomplete. Affirmations shows one of them.",
    "SUGGESTION_STYLES": "Left-border colors for AI suggestion types: priority, chunk, deadline, quick-win, nudge.",
    "SUGGESTION_LABELS": "Human labels for those suggestion types, shown above each card.",
    "GENDER_OPTIONS": "The profile form's gender select. Empty string and prefer-not-to-say are both offered.",
    "DAY_LABELS": "Sunday-first labels. Index matches Date.getDay and the schedule.days numbers.",
    "DOMAIN_RE": "Hostname check used by isValidDomain after normalizeDomain strips protocol and path.",
    "CATEGORIES": "Labels a site can belong to. categoryForDomain returns one of these or Custom.",
    "POPULAR_SITES": "The chips in Add Website. altDomains lets twitter.com count as the same site as x.com.",
    "PRESETS": "One-click blocklists. PresetPicker merges them in and never deletes sites you already added.",
    "PAUSE_PRESETS": "15 minutes, 30 minutes, 1 hour, and until 08:00 tomorrow.",
    "DEFAULT_RULES": "Shield off, empty lists, weekdays 09:00–17:00, not paused. blockingStore starts here until GET /blocking returns.",
    "EXTENSION_ID": "VITE_EXTENSION_ID. If unset, sendToExtension does nothing and the Chrome extension keeps its own login.",
    "queryClient": "One TanStack Query cache. UserContext calls invalidateQueries on socket events. No screen calls useQuery, and QueryProvider is not mounted, so those invalidations do not refresh the lists you see.",
    "themeVars": "Five unused palettes (calm, focus, night, highContrast, minimal). The live theme is only dark/light, set by App on data-theme.",
    "scheduled": "Map from task id to the timer id from setTimeout, so a task never has two deadline alarms.",
    "tabAlertSound": "Howler player for /sounds/tab-alert.mp3 at half volume. FocusOverlay plays it when the alert state starts.",
    "socket": "The single Socket.IO client. connectSocket sets auth.token and connects. disconnectSocket drops it on logout.",
    "AppBlocker": "Capacitor plugin named AppBlocker. On the web it loads AppBlockerWeb, which reports every permission denied. No React screen calls it yet.",
    "hoursLeft": "Hours until due. A task with no due date is treated as 168 hours away so it is not scored as urgent.",
    "urgency": "Near 1 when the deadline is imminent, near 0.1 when it is far or missing. The exponential falls off over about two days (the 48).",
    "taskDiff": "How big the task is, estimate/120, capped at 1. A 30-minute task is 0.25; two hours or more is 1.",
    "userE": "Your energy divided by 5, so level 1 is 0.2 and level 5 is 1. Compared with taskDiff.",
    "energyMatch": "1 when the task size matches your energy, lower when they differ. The 0.5 stops a mismatch from zeroing the score.",
    "dreadInverse": "Higher when dread is low, so an easy-feeling task ranks a bit higher. Dread 1 → 1, dread 5 → 0.5.",
    "timeFit": "1.2 if the estimate is 45 minutes or less, otherwise 0.9. Short tasks are easier to start.",
    "sortedTasks": "A copy of the open tasks sorted by scoreTask, highest first. Index 0 is the row that gets the Next badge.",
    "daily": "Today's tasksCompleted and totalSessionMins from GET /stats/daily.",
    "whatNext": "The single task from GET /tasks/what-next?energyLevel=. Null means the list is empty or the request failed.",
    "streak": "How many days back from today, up to 7, have a completed task. Today may be empty; the count stops at the first gap after today.",
    "linkedTaskId": "The task id chosen in the timer dropdown. Sent as taskId on POST /sessions. Empty string means a free session.",
    "dashOffset": "How much of the ring to hide. 0 means the ring is full (no time elapsed). CIRCUMFERENCE means the ring is empty.",
    "progress": "Fraction of the phase already used: 1 - seconds/total. The ring stroke uses this.",
    "saveState": "idle, saving, saved, or error. The Focus Shield page shows this next to the title. There is no Save button; local changes debounce into PUT /blocking.",
    "skipNextSave": "Starts true so the first GET /blocking does not immediately PUT the same rules back.",
    "local": "The editable copy of blocking rules on the Focus Shield page. Every toggle writes here. The effect on local autosaves.",
    "token": "The access token in React state. The copy that Axios actually sends is localStorage accessToken, written by saveToken.",
    "user": "The logged-in profile object. Null means ProtectedRoute renders Auth.",
    "loading": "True until UserProvider finishes the first localStorage read. ProtectedRoute renders nothing during that moment so Auth does not flash.",
    "theme": "App's dark or light string. Written onto <html data-theme> and localStorage bb-theme. This is not the unused five-palette themeStore.",
    "sidebarOpen": "Whether the desktop sidebar is slid open. The backdrop and the menu button flip it. It is component state, not uiStore.",
    "moreOpen": "Whether the mobile More sheet is open.",
    "energy": "Integer 1–5 from EnergyContext, persisted as bb-energy. Home refetches 'what next' when it changes. TodoList rescores and refetches suggestions.",
    "shieldRules": "The blocking rules sitting in useBlockingStore. Home and FocusTimer load them. FocusShieldPage saves them.",
    "distractionCount": "How many times the 800ms timer fired during this focus session. Posted with the session so the shield page can show 'distractions today'.",
}

FN = {
    "Sidebar": "Left navigation. Renders NAV_ITEMS, SECONDARY_NAV, connector links to /connectors, the compact energy control, coffee, theme, and logout. It does not fetch data.",
    "TopBar": "The bar above the page. The title is whichever nav item matches the URL. Initials come from the user name. Buttons open the sidebar, the More sheet, connectors, feedback, theme, settings, and logout.",
    "BottomNav": "Phone navigation: the four primary routes plus Profile. CSS hides it on wide screens.",
    "SheetConnectors": "The connector rows inside the More sheet. On open it GET /integrations/status. Connect redirects to the OAuth URL. Sync POSTs. Disconnect DELETEs.",
    "MoreSheet": "The slide-up sheet on small screens: secondary links, SheetConnectors, energy, coffee, theme, logout.",
    "DevNoticeBanner": "Static 'under development' notice. It does not read state. Two text lengths; CSS picks one.",
    "ProtectedRoute": "If UserProvider is still loading, render nothing. If there is no user, render Auth. Otherwise render the page.",
    "App": "Owns theme, both menus, and the route table. Wraps everything in EnergyProvider. Sidebar, overlay, top bar, banner, bottom nav, and More sheet render only when user is set.",
    "logout": "Clears user and token through UserProvider (which also clears localStorage and tells the extension). Closes both menus.",
    "Auth": "Google sign-in only. Posts the Google credential to /auth/google, then setUser, setToken, and navigates to /.",
    "handleGoogleCredential": "The callback Google calls with an id token. The backend verifies it and returns { user, token }.",
    "initGoogleIdentity": "Initializes Google Identity Services, renders Google's real button over our styled one, and also tries One Tap. Returns false if the script or client id is not ready.",
    "Home": "Today page. Greeting, energy, one recommended task, three stats, quick links, shield status, and a tip that depends on energy.",
    "loadStats": "GET /stats/daily for the tiles and GET /stats/weekly to count the streak.",
    "loadWhatNext": "GET /tasks/what-next?energyLevel= plus the current energy. Sets hasTasks from whether a task came back.",
    "whatNextReason": "Builds the sentence under the recommended task from due time, estimate, and dread. Does not call the network.",
    "FeedbackCTACard": "A card with one button that opens the feedback URL.",
    "EnergyControl": "Reads and writes EnergyContext. compact=true is the five dots in the sidebar. Otherwise the big emoji buttons on Today.",
    "setEnergy": "Stores the level in React state and in localStorage bb-energy.",
    "Logo": "Draws the JB mark. variant full adds the wordmark. The gradient id includes size and variant so two logos on one page do not clash.",
    "JBIcon": "The SVG paths for the monogram. mono-dark and mono-light are solid; anything else uses the purple-to-cyan gradient.",
    "useGradId": "Unused. Logo builds its own gradient id instead.",
    "Affirmations": "A div that shows one sentence. Parents hold a ref and call random() or messageForContext().",
    "TodoList": "Open tasks, brain dump, and suggestion cards. Ranks tasks locally with scoreTask and also asks the server for AI suggestions.",
    "DreadMeter": "Five pips. Click or Enter calls onChange with 1–5. Add-task, edit, and each row all use it.",
    "PriorityBadge": "Shows task.aiPriority as High, Medium, or Low. Renders nothing if the server sent no level.",
    "AddTaskRow": "One title field. Enter submits. Tab or '+ Details' reveals due date, minutes (default 30), and dread (default 3).",
    "submit": "Calls the onAdd prop, then clears the form and focuses the title again.",
    "load": "GET /tasks and, on the task page, keeps only tasks that are not completed. Calendar and the deadline page keep a wider set.",
    "fetchSuggestions": "GET /tasks/ai/suggestions and GET /recommendations/mindfulness in parallel. A mindfulness hit is inserted as a nudge card. Dismissed ids are filtered out.",
    "add": "POST /tasks. If the new task has a due date, schedule a notification and tell the user one was set.",
    "complete": "Shows the check animation for 450ms, then PUT /tasks/:id/complete, clears the deadline timer, and reloads.",
    "autoChunk": "POST /tasks/:id/auto-chunk so the server splits the task into subtasks, then reloads.",
    "saveEdit": "PUT /tasks/:id with the edit fields, closes the editor, reloads.",
    "updateDread": "PUT only dreadScore and patches that one task in state so the list does not reload.",
    "submitDump": "POST /tasks/brain-dump with the text and current energy. Switches the view back to the list.",
    "acceptSuggestion": "Quick-win completes that task. Mindfulness navigates to /mindful. Prioritize scrolls to the task row. Then the card is removed.",
    "dismissSuggestion": "Removes the card and remembers the id so the next fetch does not bring it back.",
    "scoreTask": "One number per task. Bigger sorts first. urgency × energyMatch × dreadInverse × timeFit.",
    "fmtDue": "Overdue, 'due in Nh' under 24 hours, or a calendar date.",
    "showReward": "Sets an emoji that a CSS burst shows, then clears it after 900ms.",
    "FocusTimer": "Countdown ring. On a finished work phase it POSTs /sessions and tells FocusOverlay the session ended.",
    "loadTasks": "GET /tasks and keeps incomplete ones for the dropdown.",
    "handleComplete": "Work phase: count the session, read distraction count from the overlay, reset it, POST /sessions with type, minutes, distractions, bb-energy, and optional taskId. Break phase only changes the affirmation.",
    "toggle": "Flips active. Pausing also calls setFocusActive(false) so the overlay leaves the focused state.",
    "reset": "Stops the interval, leaves focus, forces the work phase, and restores workMins × 60.",
    "switchPhase": "Flips work/break without counting a completed session.",
    "fmt": "Turns a second count into m:ss.",
    "FocusOverlay": "Mounted once in App, beside the routes. Watches document visibility only while a session is focused.",
    "setFocusActive": "Module-level bridge. FocusTimer calls this; the overlay registers _bridge on mount. That is how a route child talks to a component that is not its parent.",
    "getDistractionCount": "Returns the ref the overlay increments. FocusTimer reads it when a work phase ends.",
    "resetDistractionCount": "Zeros that ref at the start of the next session.",
    "setState": "Writes both the ref (so the visibility listener is not stale) and React state (so the alert card appears).",
    "onImBack": "Alert → focused. The countdown keeps running; this only dismisses the card.",
    "onEndSession": "Alert → idle and clears the debounce. It does not by itself stop FocusTimer's interval.",
    "Dashboard": "Four tiles plus a 7-day bar chart and a 30-day line chart from /stats/daily, /weekly, and /monthly.",
    "processWeekly": "Builds seven day buckets ending today and drops completed tasks and session minutes into them.",
    "processMonthly": "Same for 30 days. Labels are M/D.",
    "ChartLegend": "Colored swatches. It does not read chart data.",
    "Calendar": "FullCalendar month view of tasks. Clicking a day prompts for a title and POSTs a task. Clicking an event prompts for a new due time and PUTs it.",
    "handleDateClick": "prompt() for a title, POST /tasks with that dueAt, then load() immediately (the reload can race the POST).",
    "handleEventClick": "prompt() for a new datetime, PUT /tasks/:id, then load().",
    "DeadlineTimer": "Lists tasks that have dueAt. Reschedule navigates to /calendar. It does not edit the date itself.",
    "ConnectorsPage": "Full-page version of the three connectors, plus toasts and the OAuth return query string.",
    "fmtDate": "Short local date-time for 'last synced'.",
    "showToast": "Sets toast state and clears it after 4 seconds.",
    "handleConnect": "GET the connector's urlEndpoint and set window.location to that OAuth URL.",
    "handleSync": "POST the sync endpoint. The page toast includes result.synced and result.created.",
    "handleDisconnect": "DELETE /integrations/:id and refresh status.",
    "Mindfulness": "The live function starts at the third Mindfulness in the file. The first two are inside a block comment. It plays one of three mp3s and stops if the tab is hidden.",
    "formatTime": "Milliseconds to m:ss.",
    "ProfileSettings": "Edits name, email, gender through updateUser, and saves preferredTheme both on the server and into App's theme state.",
    "handleProfileSave": "preventDefault, then updateUser. The success or error string is profileMsg.",
    "handleThemeSave": "PUT preferredTheme, then onThemeChange so the shell updates before the next navigation.",
    "handleThemeSelect": "Sets the local highlight and immediately saves. There is no separate Save button for theme.",
    "getInitials": "First letters of the first two words, or the email's first character. Same rule as the top-bar avatar.",
    "CoffeeIcon": "The cup SVG next to the support link.",
    "UserProvider": "On mount, hydrates token and user from localStorage, mirrors them to the Chrome extension, and opens the socket.",
    "sendToExtension": "chrome.runtime.sendMessage to EXTENSION_ID. Swallows the 'no extension' error.",
    "saveToken": "React state plus localStorage accessToken. Axios reads localStorage, not React state.",
    "saveUser": "React state plus localStorage user. Passing null removes the key. Logout uses this.",
    "updateUser": "PUT /profile via updateProfile, then merges the response onto the stored user.",
    "EnergyProvider": "Wraps the shell in App.jsx so Home, EnergyControl, and TodoList share one number.",
    "scheduleDeadline": "If the task is open and due in the future, replace any previous timer and fire notify at dueAt.",
    "clearDeadline": "cancel the timer for one task id. complete() and the effect cleanup call this.",
    "notify": "Shows a Notification only if permission is already granted. App.jsx is what asks for permission.",
    "normalizeDomain": "Lowercase, strip protocol, path, query, hash, and a leading www.",
    "isValidDomain": "True when the normalized string matches DOMAIN_RE.",
    "categoryForDomain": "Popular-site category, or Custom.",
    "isScheduleActiveNow": "True when the schedule is enabled, today is a selected weekday, and now is inside start–end. A window that crosses midnight is not handled.",
    "isPaused": "True when pausedUntil is still in the future.",
    "computePauseUntil": "tomorrow means 08:00 next calendar day. Otherwise add the preset or custom minutes.",
    "formatClockTime": "Locale time like 3:05 PM, used in the paused status sentence.",
    "getShieldStatus": "The single status label. Order: off, paused, active because a session is running, active because the schedule window is open, otherwise armed.",
    "mergeDomains": "Append entries whose domain is not already in the list, and mark them enabled.",
    "FocusShieldPage": "Loads GET /blocking into local state and the Zustand store, then PUTs local 600ms after each change.",
    "update": "Shallow-merges a patch into local, which schedules the autosave.",
    "updateSchedule": "Same, but the patch is applied to local.schedule.",
    "toggleDay": "Adds or removes a weekday number and keeps the array sorted.",
    "addApp": "Appends a blocked-app entry. Enforcement is native; this page only stores the name.",
    "removeApp": "Drops one blocked app by index.",
    "handleExport": "Downloads jumpybrain-focus-shield-rules.json containing blocked sites and the whitelist.",
    "handleImportFile": "Reads a JSON file and appends domains that are not already present.",
    "AppEntryList": "Renders blocked apps with a remove button.",
    "AppAddRow": "Two inputs: display name and optional package name.",
    "handleAdd": "Trims the name and calls onAdd, then clears the inputs.",
    "WebsiteListManager": "One list, used twice: blocked sites and whitelist. Search, selection, bulk enable/disable/delete, add sheet, edit sheet.",
    "toggleSelect": "Adds or removes a domain from the selection Set.",
    "clearSelection": "Empties that Set.",
    "updateEntry": "Maps the array, replacing the entry with this domain. onChange bubbles to FocusShieldPage.update, which autosaves.",
    "deleteEntry": "Filters the domain out and also drops it from the selection.",
    "bulkSetEnabled": "Sets enabled on every selected row.",
    "bulkDelete": "Removes every selected row.",
    "WebsiteRow": "Checkbox, name, domain, category badge, enable switch, and the ⋮ menu.",
    "RowMenu": "Opens a menu that closes on outside click or Escape.",
    "AddWebsiteSheet": "Searchable popular chips plus a custom domain field. onAdd receives an array of one entry.",
    "addPopular": "Adds the chip's domain unless existingValues already has it.",
    "addCustom": "Normalizes and validates. Sets an error string instead of adding when the domain is bad or duplicate.",
    "handleClose": "Clears the sheet's fields, then calls the parent's onClose.",
    "handleCustomKey": "Enter in the custom field calls addCustom.",
    "EditRuleSheet": "Copies the entry into form state when opened. Save re-validates the domain.",
    "handleSave": "normalizeDomain + isValidDomain, then onSave with the cleaned domain.",
    "Sheet": "Shared dialog. Escape or backdrop calls onClose. Renders null when open is false. CSS decides bottom sheet vs centered modal.",
    "PauseControl": "Hidden when the shield is off. If paused, shows the resume time. Otherwise preset buttons and a custom minute field.",
    "PresetPicker": "Applies one preset by merging its domains into the current block list.",
    "apply": "mergeDomains then onApply. Shows 'Applied' for 2 seconds.",
    "ShieldStatusCard": "Dashboard variant shows counts. Session variant lists up to five enabled blocked sites. Both link to /blocking.",
    "Toggle": "A button with role=switch. Click calls onChange with the opposite boolean. It does not store the boolean itself.",
    "createSSEStream": "Fetches an SSE URL with the bearer token, splits data: lines, and calls onChunk with parsed.text until [DONE]. Returns an abort function. Only useAIStream calls it, and no screen calls useAIStream.",
    "useAIStream": "Unused by the screens. Brain dump and suggestions use ordinary api.post and api.get instead.",
    "useTimer": "Unused. The Focus page keeps its own seconds state. This hook would tick timerStore.elapsed.",
    "useTheme": "Unused. Would write the five palette CSS variables. App writes data-theme for dark/light instead.",
    "useFocusMode": "Unused. Would emit FOCUS_LOST on the socket after 800ms. The live path is FocusOverlay's visibility listener.",
    "QueryProvider": "Would provide queryClient. main.jsx never renders it.",
    "connectSocket": "Sets socket.auth to { token } and connects.",
    "disconnectSocket": "Disconnects and forgets the instance so the next login creates a fresh one.",
    "getSocket": "Returns the singleton, creating it with autoConnect false if needed. The URL is the API origin with /api stripped.",
    "checkPermissions": "On the web stub, returns denied for usage stats, accessibility, and Family Controls.",
    "setBlockingRules": "On the web stub, returns { ok: false }. The native Android and iOS plugins are the real implementations.",
}


def decl_meaning(statement: str) -> str:
    import re
    m = re.match(
        r"(?:export\s+)?(?:const|let|var)\s+(?:\[([^\]]+)\]|\{([^}]+)\}|([A-Za-z0-9_]+))\s*=\s*(.*)",
        statement,
    )
    if not m:
        return f"declaration `{statement[:220]}`."
    names = [p.strip() for p in re.split(r"[, ]+", (m.group(1) or m.group(2) or m.group(3) or "")) if p.strip()]
    rhs = (m.group(4) or "").strip()
    bits = []
    for name in names:
        if name in DECL:
            bits.append(f"`{name}`: {DECL[name]}")
    if bits:
        return " ".join(bits) + f" The code is `{statement[:180]}`."
    if "useState" in rhs or "useState" in statement:
        return (
            f"React state `{', '.join(names)}`. The value survives re-renders. Calling the setter re-renders this component. `{statement[:180]}`"
        )
    if "useRef" in statement:
        return f"A ref `{', '.join(names)}`. `.current` survives re-renders and writing it does not re-render. `{statement[:180]}`"
    if "useMemo" in statement:
        return f"A memoized value `{', '.join(names)}`, recomputed only when its dependency array changes. `{statement[:180]}`"
    if "useCallback" in statement:
        return f"A memoized function `{', '.join(names)}`. `{statement[:180]}`"
    return (
        f"`{', '.join(names)}` is assigned `{rhs[:160]}`. Later lines in this function read that name."
    )


def fn_blurb(name: str) -> str:
    return FN.get(name, "")
